### ISSUE TITLE
Two events triggering at once, a bug not present in another version of Altimit movement

### ISSUE THREAD

**Issue by WinterVein** [TyruswooStudio/Tyruswoo_AltimitMovement-MZ#2]
Hello Tyrus Woo, I really like your version of Altimit movement, however it has a bug where two events can be triggered back to back if you're standing right between them when triggered, Like so:

![image](https://github.com/TyruswooStudio/Tyruswoo_AltimitMovement-MZ/assets/8573908/78a708d6-2f6d-45fa-bffa-8e623bcfcf5e)

This bug is not present in the other version of Altimit Movement MZ made by Ve Lee and I'd really like it if it was fixed in the tyruswoo version

https://github.com/ve-lee/AltimitMovement-MZ/tree/main/js/plugins

**Comment by McKathlin** [comment]
Hi @WinterVein, thanks for bringing this issue to our attention! If you don't need to recalculate the collision mesh after in-game tile changes, Ve Lee's edition of Altimit Movement should meet all your needs (and you're probably using it already). Thanks for letting us know it's there!

Anyway, we wanted you to know that @Tyruswoo and I have started working on this and we expect to have a fix released by the end of the week. :)

**Comment by McKathlin** [comment]
Hello again @WinterVein, we'd like to thank you for your patience as we work on this. It turns out that, while VeLee's Altimit build fixes several bugs (and might introduce others, so we're not ready to merge it into ours yet!), the two-event trigger bug you found in Tyruswoo Altimit Movement is also in VeLee's build; I've reproduced the bug in both.

We're still working on a fix, but it may take longer than originally estimated, since apparently no one else has fixed it yet.

**Comment by McKathlin** [comment]
Hi @WinterVein,

We have a possible fix ready. This doesn't eliminate all simultaneously triggering events, as sometimes action-oriented games are _supposed_ to let multiple events trigger at once. What we've done is make it so that if two events are triggered at once, the second one only runs if it's still on the right page and within appropriate proximity _after_ the first event finishes running.

Please follow this link to our latest release:
[Tyruswoo Altimit Movement v0.7.0](https://github.com/TyruswooStudio/Tyruswoo_AltimitMovement-MZ/releases/tag/v0.7.0)

Thanks again for reporting this issue and helping us improve Tyruswoo Altimit Movement!

**Comment by WinterVein** [comment]
Awesome! Thank you so much!
